services:
  app:
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost 127.0.0.1 testserver
      - CSRF_TRUSTED_ORIGINS=http://localhost http://127.0.0.1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?connect_timeout=1
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file: []  # Explicit empty array

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
